version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo npm install -g esy@next

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "esy.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      # build
      - run: esy install

      # run tests!
      - run: esy b
      - run: esy dune exec ExamplesTests

      - save_cache:
          paths:
            - node_modules
            - ~/.esy
            - examples/bs-3.1.5/node_modules/
            - examples/example-project/node_modules/
            - examples/example-es6-imports/node_modules/
            - examples/example-react/node_modules/
            - examples/example-esy-dune-project/node_modules/
          key: v2-dependencies-{{ checksum "esy.json" }}

      - store_artifacts:
          path: ./_build/default/bin/Bin.exe
          destination: bin.linux.exe

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    working_directory: ~/repo
    steps:
      - run:
          name: "Publish Release on GitHub"
          command: |
            FILE=./_build/default/bin/Bin.exe
            VERSION=$(my-binary --version)
            curl -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: $(file -b --mime-type $FILE)" --data-binary @$FILE "https://uploads.github.com/repos/jaredly/reason-language-server/releases/${CIRCLE_TAG}/assets?name=bin.linux.exe"

